In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
df_set = pd.read_csv('C:/Users/Dell/OneDrive/Desktop/Komal/Internships/VerveBridge/NBA Draft Dataset All Years Combine.csv')
df_set.head()

Col_1            Player  Year  Draft pick  Height (No Shoes)  \
0      0    Andre Drummond  2012         9.0              81.75   
1      1  Andrew Nicholson  2012        19.0              80.50   
2      2     Anthony Davis  2012         1.0              81.25   
3      3   Arnett Moultrie  2012        27.0              81.50   
4      4     Austin Rivers  2012        10.0              75.50   

   Height (With Shoes)  Wingspan  Standing reach  Vertical (Max)  \
0                83.75     90.25           109.5            33.5   
1                81.50     88.00           107.0            30.5   
2                82.50     89.50           108.0             NaN   
3                82.75     86.25           106.5            37.5   
4                77.00     79.25            96.5            37.5   

   Vertical (Max Reach)  Vertical (No Step)  Vertical (No Step Reach)  Weight  \
0                 143.0                31.5                     141.0   279.0   
1                 137.5                28.5                     135.5   234.0   
2                   NaN                 NaN                       NaN   222.0   
3                 144.0                33.5                     140.0   233.0   
4                 134.0                32.5                     129.0   203.0   

   Body Fat  Hand (Length)  Hand (Width)  Bench  Agility  Sprint  
0       7.5           9.50          9.50   10.0    10.83    3.39  
1       7.6          10.00         10.75   10.0    11.89    3.67  
2       7.9           9.00          8.50    NaN      NaN     NaN  
3       7.7           9.25          9.25   10.0    11.32    3.22  
4       6.2           8.50         10.00    1.0    11.54    3.32

In [3]:
df_set.shape

(306, 19)

DATA CLEANING WITH ANALYZING FEATURES

In [4]:
df_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Col_1                     306 non-null    int64  
 1   Player                    306 non-null    object 
 2   Year                      306 non-null    int64  
 3   Draft pick                215 non-null    float64
 4   Height (No Shoes)         306 non-null    float64
 5   Height (With Shoes)       306 non-null    float64
 6   Wingspan                  306 non-null    float64
 7   Standing reach            306 non-null    float64
 8   Vertical (Max)            257 non-null    float64
 9   Vertical (Max Reach)      257 non-null    float64
 10  Vertical (No Step)        258 non-null    float64
 11  Vertical (No Step Reach)  258 non-null    float64
 12  Weight                    305 non-null    float64
 13  Body Fat                  305 non-null    float64
 14  Hand (Leng

In [5]:
df_set.isnull().sum()

Col_1                         0
Player                        0
Year                          0
Draft pick                   91
Height (No Shoes)             0
Height (With Shoes)           0
Wingspan                      0
Standing reach                0
Vertical (Max)               49
Vertical (Max Reach)         49
Vertical (No Step)           48
Vertical (No Step Reach)     48
Weight                        1
Body Fat                      1
Hand (Length)                 0
Hand (Width)                  0
Bench                       157
Agility                      52
Sprint                       53
dtype: int64

In [6]:
df_set['Draft pick'].unique()

array([ 9., 19.,  1., 27., 10., 33.,  3.,  6., 55., 46.,  4., 42., 35.,
       nan, 22., 30.,  7., 34., 24., 21., 31., 12., 14., 23., 13., 47.,
       39., 44., 51., 49., 59., 29., 11.,  2., 43., 26., 15., 36., 28.,
       37., 38., 58., 16., 18.,  8.,  5., 32., 25., 17., 41., 40., 53.,
       50., 52., 56., 48., 20., 60., 45., 54.])

In [7]:
df_set['Draft pick'].describe(include = 'all')

count    215.000000
mean      29.000000
std       16.127413
min        1.000000
25%       15.000000
50%       29.000000
75%       42.000000
max       60.000000
Name: Draft pick, dtype: float64

In [8]:
df_set['Draft pick'].value_counts()

Draft pick
9.0     5
33.0    5
10.0    5
6.0     5
34.0    5
22.0    5
42.0    5
14.0    5
37.0    5
18.0    5
49.0    5
36.0    5
17.0    5
8.0     5
13.0    4
44.0    4
24.0    4
12.0    4
58.0    4
51.0    4
28.0    4
23.0    4
30.0    4
21.0    4
19.0    4
46.0    4
27.0    4
25.0    4
38.0    4
56.0    4
40.0    4
43.0    4
41.0    4
11.0    4
45.0    3
55.0    3
39.0    3
31.0    3
47.0    3
35.0    3
3.0     3
4.0     3
7.0     3
48.0    3
15.0    3
2.0     3
26.0    3
29.0    3
59.0    3
32.0    3
5.0     3
20.0    3
50.0    3
52.0    2
16.0    2
1.0     1
53.0    1
60.0    1
54.0    1
Name: count, dtype: int64

In [9]:
imputer_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer_median = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer_mode = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')

In [10]:
 #applying mean
df_set['Draft pick'] = imputer_mean.fit_transform(np.array(df_set['Draft pick']).reshape(-1,1))

In [11]:
df_set['Draft pick'].isnull().sum().any()

np.False_

In [12]:
df_set['Draft pick'] = df_set['Draft pick'].astype(int)

Vertical (max) Column

In [13]:
df_set["Vertical (Max)"].unique()

array([33.5, 30.5,  nan, 37.5, 32.5, 39. , 39.5, 41.5, 37. , 33. , 34. ,
       31. , 29.5, 36.5, 34.5, 40. , 38. , 30. , 35. , 31.5, 40.5, 35.5,
       38.5, 36. , 42. , 32. , 29. , 41. , 44. , 43.5, 28.5, 25. , 43. ,
       28. ])

In [14]:
type(df_set["Vertical (Max)"][0])

numpy.float64

In [15]:
df_set["Vertical (Max)"].describe(include = "all")

count    257.000000
mean      35.638132
std        3.595704
min       25.000000
25%       33.000000
50%       35.500000
75%       38.000000
max       44.000000
Name: Vertical (Max), dtype: float64

In [16]:
df_set["Vertical (Max)"].value_counts()

Vertical (Max)
35.5    22
36.5    16
34.5    15
37.5    15
36.0    13
34.0    12
38.0    12
37.0    12
32.5    11
33.5    10
39.5    10
31.0    10
40.5     9
35.0     9
32.0     8
38.5     8
31.5     8
29.5     7
33.0     6
41.5     6
40.0     6
29.0     4
30.0     3
39.0     3
30.5     3
28.5     3
41.0     3
44.0     3
43.5     3
43.0     3
42.0     2
25.0     1
28.0     1
Name: count, dtype: int64

In [17]:
df_set["Vertical (Max)"] = imputer_mode.fit_transform(np.array(df_set["Vertical (Max)"]).reshape(-1,1))

In [18]:
df_set["Vertical (Max)"].isnull().any()

np.False_

Vertical (Max reach) Column

In [19]:
df_set["Vertical (Max Reach)"].unique()

array([143. , 137.5,   nan, 144. , 134. , 141. , 139. , 135. , 138. ,
       132. , 141.5, 125.5, 136.5, 140. , 142. , 134.5, 129. , 133. ,
       135.5, 137. , 140.5, 146. , 139.5, 138.5, 145.5, 143.5, 127. ,
       129.5, 142.5, 145. , 136. , 144.5, 131.5, 130.5, 133.5, 126.5,
       128.5, 132.5, 127.5, 128. , 147. ])

In [20]:
df_set["Vertical (Max Reach)"].describe()

count    257.000000
mean     138.093385
std        4.220605
min      125.500000
25%      135.000000
50%      138.500000
75%      141.500000
max      147.000000
Name: Vertical (Max Reach), dtype: float64

In [21]:
df_set["Vertical (Max Reach)"].value_counts()

Vertical (Max Reach)
138.0    20
139.5    14
141.5    13
134.0    12
136.5    12
142.0    12
141.0    12
138.5    12
137.5    11
139.0    11
144.0    11
135.0     9
140.5     9
134.5     8
140.0     8
137.0     7
143.0     6
136.0     6
142.5     6
143.5     6
133.5     6
133.0     5
132.0     5
135.5     5
144.5     4
145.0     3
132.5     3
145.5     2
131.5     2
129.5     2
129.0     2
127.0     2
128.0     2
130.5     2
126.5     2
125.5     1
146.0     1
128.5     1
127.5     1
147.0     1
Name: count, dtype: int64

In [22]:
#using mean
df_set["Vertical (Max Reach)"] = imputer_mean.fit_transform(np.array(df_set["Vertical (Max Reach)"]).reshape(-1,1))

In [23]:
df_set["Vertical (Max Reach)"].isna().any()

np.False_

Vertical (No Step Reach) Column

In [24]:
df_set["Vertical (No Step Reach)"].unique()

array([141. , 135.5,   nan, 140. , 129. , 138.5, 133. , 130. , 129.5,
       134. , 127.5, 132.5, 139.5, 142. , 134.5, 131. , 122. , 136. ,
       130.5, 135. , 133.5, 137.5, 128.5, 125.5, 127. , 138. , 128. ,
       136.5, 121.5, 131.5, 122.5, 132. , 137. , 141.5, 140.5, 126.5,
       125. , 124. , 123.5, 139. , 126. , 124.5, 121. , 143. , 119. ,
       142.5, 144. ])

In [25]:
df_set["Vertical (No Step Reach)"].value_counts()

Vertical (No Step Reach)
131.0    15
133.0    14
134.5    14
132.5    12
136.0    10
129.0    10
131.5    10
135.0    10
132.0    10
138.0     9
129.5     9
133.5     8
128.0     8
135.5     8
137.0     8
134.0     7
136.5     6
127.0     6
138.5     6
140.0     6
127.5     6
130.0     6
128.5     6
137.5     6
130.5     5
126.5     5
139.5     4
139.0     4
124.5     3
123.5     3
125.5     3
141.0     2
121.0     2
122.5     2
125.0     2
124.0     2
140.5     2
142.0     1
121.5     1
122.0     1
141.5     1
126.0     1
143.0     1
119.0     1
142.5     1
144.0     1
Name: count, dtype: int64

In [27]:
df_set["Vertical (No Step Reach)"] = imputer_mean.fit_transform(np.array(df_set["Vertical (No Step Reach)"]).reshape(-1,1))

Vertical (No step) Column

In [28]:
df_set["Vertical (No Step)"] = imputer_mean.fit_transform(np.array(df_set["Vertical (No Step)"]).reshape(-1,1))

Weight and Body Fat Column

In [29]:
df_set["Weight"] = imputer_mean.fit_transform(np.array(df_set["Weight"]).reshape(-1,1))
df_set["Body Fat"] = imputer_mean.fit_transform(np.array(df_set["Body Fat"]).reshape(-1,1))

Bench Column

In [30]:
df_set["Bench"].describe()

count    149.000000
mean       9.463087
std        4.728470
min        1.000000
25%        6.000000
50%        9.000000
75%       13.000000
max       21.000000
Name: Bench, dtype: float64

In [31]:
#dropping this column because it has more that 50% null values
df_set.drop(columns = ["Bench"], inplace = True)

Agility and Sprint

In [32]:
df_set["Agility"].describe()

count    254.000000
mean      11.293307
std        0.547450
min       10.190000
25%       10.870000
50%       11.245000
75%       11.617500
max       12.940000
Name: Agility, dtype: float64

In [33]:
#using mean
df_set["Agility"] = imputer_mean.fit_transform(np.array(df_set["Agility"]).reshape(-1,1))

In [34]:
df_set["Sprint"].describe()

count    253.000000
mean       3.322292
std        0.126877
min        3.020000
25%        3.240000
50%        3.300000
75%        3.400000
max        3.810000
Name: Sprint, dtype: float64

In [35]:
#using mean
df_set["Sprint"] = imputer_mean.fit_transform(np.array(df_set["Sprint"]).reshape(-1,1))

In [36]:
df_set.head()

Col_1            Player  Year  Draft pick  Height (No Shoes)  \
0      0    Andre Drummond  2012           9              81.75   
1      1  Andrew Nicholson  2012          19              80.50   
2      2     Anthony Davis  2012           1              81.25   
3      3   Arnett Moultrie  2012          27              81.50   
4      4     Austin Rivers  2012          10              75.50   

   Height (With Shoes)  Wingspan  Standing reach  Vertical (Max)  \
0                83.75     90.25           109.5            33.5   
1                81.50     88.00           107.0            30.5   
2                82.50     89.50           108.0            35.5   
3                82.75     86.25           106.5            37.5   
4                77.00     79.25            96.5            37.5   

   Vertical (Max Reach)  Vertical (No Step)  Vertical (No Step Reach)  Weight  \
0            143.000000           31.500000                141.000000   279.0   
1            137.500000           28.500000                135.500000   234.0   
2            138.093385           30.127907                132.614341   222.0   
3            144.000000           33.500000                140.000000   233.0   
4            134.000000           32.500000                129.000000   203.0   

   Body Fat  Hand (Length)  Hand (Width)    Agility    Sprint  
0       7.5           9.50          9.50  10.830000  3.390000  
1       7.6          10.00         10.75  11.890000  3.670000  
2       7.9           9.00          8.50  11.293307  3.322292  
3       7.7           9.25          9.25  11.320000  3.220000  
4       6.2           8.50         10.00  11.540000  3.320000

In [37]:
df_set.to_csv('C:/Users/Dell/OneDrive/Desktop/Komal/Internships/VerveBridge/NBA Draft Dataset All Years Combine.csv', index = False)